### ISSUE TITLE
Wrong number of fields for signal configation

### ISSUE THREAD

**Issue by eboustou** [RphWbr/visiannot#7]
The number of fields for signal configuration is directly dependent of the number of fields in the configuration file for each signal. Video included.

eg :
vid_0 = ['/video/01', '*v1*.mp4', '_', 1]
vid_1 = ['/video/02', '*v2*.mp4', '_', 1, '%Y-%m-%dT%H-%M-%S']

**Comment by RphWbr** [comment]
I added a check for every configuration in the configuration file, so that an exception is raised if the number of elements in a configuration is wrong. See commit ab81b2820d3b4c17403aab7a22d83d21732fc285.

So, when the error occurs, it is up to the user to correct the configuration file. The configuration GUI does not adapt to a wrong configuration length.
